export const EVENT_TYPES = {
  INGRESO: "INGRESO",
  SALIDA: "SALIDA",
  VALE_ALMUERZO: "VALE_ALMUERZO",
  INICIO_ALMUERZO: "INICIO_ALMUERZO",
  FIN_ALMUERZO: "FIN_ALMUERZO"
};

export const EVENT_LABELS = {
  [EVENT_TYPES.INGRESO]: "Ingreso",
  [EVENT_TYPES.SALIDA]: "Salida",
  [EVENT_TYPES.VALE_ALMUERZO]: "Vale colacion",
  [EVENT_TYPES.INICIO_ALMUERZO]: "Inicio colacion",
  [EVENT_TYPES.FIN_ALMUERZO]: "Fin colacion"
};

export const EVENT_LCD_LABELS = {
  [EVENT_TYPES.INGRESO]: "ENTRA A TURNO",
  [EVENT_TYPES.SALIDA]: "SALE DE TURNO",
  [EVENT_TYPES.VALE_ALMUERZO]: "VALE COLACION",
  [EVENT_TYPES.INICIO_ALMUERZO]: "INICIO COLACION",
  [EVENT_TYPES.FIN_ALMUERZO]: "FIN COLACION"
};

export const EVENT_SHORT_LABELS = {
  [EVENT_TYPES.INGRESO]: "INGRESO",
  [EVENT_TYPES.SALIDA]: "SALIDA",
  [EVENT_TYPES.VALE_ALMUERZO]: "VALE",
  [EVENT_TYPES.INICIO_ALMUERZO]: "INI COL",
  [EVENT_TYPES.FIN_ALMUERZO]: "FIN COL"
};

export const FUNCTION_KEYS = {
  F1: EVENT_TYPES.INGRESO,
  F2: EVENT_TYPES.SALIDA,
  F3: EVENT_TYPES.VALE_ALMUERZO,
  F4: EVENT_TYPES.INICIO_ALMUERZO,
  F5: EVENT_TYPES.FIN_ALMUERZO
};

export function getSuccessMessage(eventType) {
  const messages = {
    [EVENT_TYPES.INGRESO]: "INGRESADO EXITOSAMENTE - OK",
    [EVENT_TYPES.SALIDA]: "SALIDA REGISTRADA - OK",
    [EVENT_TYPES.VALE_ALMUERZO]: "VALE COLACION - OK",
    [EVENT_TYPES.INICIO_ALMUERZO]: "INICIO COLACION - OK",
    [EVENT_TYPES.FIN_ALMUERZO]: "FIN COLACION - OK"
  };

  return messages[eventType] ?? "EVENTO REGISTRADO";
}

export function getOfflineSuccessMessage(eventType) {
  const messages = {
    [EVENT_TYPES.INGRESO]: "OK INGRESO - REGISTRADO OFFLINE",
    [EVENT_TYPES.SALIDA]: "OK SALIDA - REGISTRADO OFFLINE",
    [EVENT_TYPES.VALE_ALMUERZO]: "OK VALE - REGISTRADO OFFLINE",
    [EVENT_TYPES.INICIO_ALMUERZO]: "OK INICIO COL - REGISTRADO OFFLINE",
    [EVENT_TYPES.FIN_ALMUERZO]: "OK FIN COL - REGISTRADO OFFLINE"
  };

  return messages[eventType] ?? "REGISTRADO OFFLINE";
}

export function getOnlineLcdLines(eventType, employeeName = "") {
  const lines = {
    [EVENT_TYPES.INGRESO]: ["INGRESADO", "EXITOSAMENTE", "OK"],
    [EVENT_TYPES.SALIDA]: ["SALIDA", "REGISTRADA", "OK"],
    [EVENT_TYPES.VALE_ALMUERZO]: ["VALE COLACION", "OK"],
    [EVENT_TYPES.INICIO_ALMUERZO]: ["INICIO COL", "OK"],
    [EVENT_TYPES.FIN_ALMUERZO]: ["FIN COL", "OK"]
  };

  return employeeName ? [...(lines[eventType] ?? ["REGISTRADO", "OK"]), employeeName] : lines[eventType] ?? ["OK"];
}

export function getOfflineLcdLines(eventType) {
  const lines = {
    [EVENT_TYPES.INGRESO]: ["OK INGRESO", "REGISTRADO", "OFFLINE"],
    [EVENT_TYPES.SALIDA]: ["OK SALIDA", "REGISTRADO", "OFFLINE"],
    [EVENT_TYPES.VALE_ALMUERZO]: ["OK VALE", "REGISTRADO", "OFFLINE"],
    [EVENT_TYPES.INICIO_ALMUERZO]: ["OK INICIO COL", "REG OFFLINE"],
    [EVENT_TYPES.FIN_ALMUERZO]: ["OK FIN COL", "REG OFFLINE"]
  };

  return lines[eventType] ?? ["REG OFFLINE"];
}
