export const EVENT_TYPES = {
  INGRESO: "INGRESO",
  SALIDA: "SALIDA",
  VALE_ALMUERZO: "VALE_ALMUERZO",
  INICIO_ALMUERZO: "INICIO_ALMUERZO",
  FIN_ALMUERZO: "FIN_ALMUERZO"
};

export const EVENT_LABELS = {
  [EVENT_TYPES.INGRESO]: "Ingreso",
  [EVENT_TYPES.SALIDA]: "Salida",
  [EVENT_TYPES.VALE_ALMUERZO]: "Vale de almuerzo",
  [EVENT_TYPES.INICIO_ALMUERZO]: "Inicio almuerzo",
  [EVENT_TYPES.FIN_ALMUERZO]: "Fin almuerzo"
};

export const FUNCTION_KEYS = {
  F1: EVENT_TYPES.INGRESO,
  F2: EVENT_TYPES.SALIDA,
  F3: EVENT_TYPES.VALE_ALMUERZO,
  F4: EVENT_TYPES.INICIO_ALMUERZO,
  F5: EVENT_TYPES.FIN_ALMUERZO
};

export function getSuccessMessage(eventType) {
  const messages = {
    [EVENT_TYPES.INGRESO]: "INGRESO REGISTRADO",
    [EVENT_TYPES.SALIDA]: "SALIDA REGISTRADA",
    [EVENT_TYPES.VALE_ALMUERZO]: "VALE ALMUERZO REGISTRADO",
    [EVENT_TYPES.INICIO_ALMUERZO]: "INICIO ALMUERZO REGISTRADO",
    [EVENT_TYPES.FIN_ALMUERZO]: "FIN ALMUERZO REGISTRADO"
  };

  return messages[eventType] ?? "EVENTO REGISTRADO";
}
